### ISSUE TITLE
Working with <slot />

### ISSUE THREAD

**Issue by jakobrosenberg** [hyperlab/svelte-error-boundary#2]
Any chance this is doable?

```html
<!-- MyWidget.svelte -->
<script>
  import {Boundary} from "@crownframework/svelte-error-boundary";
</script>
  
<Boundary onError={console.log}>
  <slot />
</Boundary>
```

**Comment by jonatansberg** [comment]
Seems to work just fine:  
https://svelte.dev/repl/db3d32c85802449ca15926f45bc0f46a?version=3.29.7

Or, am I missing something?

**Comment by jakobrosenberg** [comment]
Right you are. I'm not sure why I got different results.

Thanks for quick reply.
